### ISSUE TITLE
pyOpenSSL version in setup.py

### ISSUE THREAD

**Issue by danielfaust** [google/identity-toolkit-python-client#10]
Hi,

pyOpenSSL is locked to version 14. Current version is >=15. Installing identity-toolkit-python-client
downgrades the system or venv to 14.

http://stackoverflow.com/questions/33506571/pyopenssl-version-in-identity-toolkit-python-client

**Comment by liujin-google** [comment]
Thanks for the report. Fixed just now.

**Comment by danielfaust** [comment]
It still needs to get pushed over to pypy with a version bump.

**Comment by RevolutionTech** [comment]
Updated the library on PyPi. Thanks Daniel!
