### ISSUE TITLE
Provide identity-toolkit on app engine

### ISSUE THREAD

**Issue by kno10** [google/identity-toolkit-python-client#14]
It is completely incomprehensible how to use this with Google App Engine.

In particular, it is crazy that we have to "vendor" install a dozen dependencies.

All identity-toolkit libraries should be preinstalled ("runtime provided") by Google App Engine:
https://cloud.google.com/appengine/docs/python/tools/libraries27

and a simple example of a federated-login app engine application should be added, that can be test-driven locally. The example at https://github.com/googlesamples/identity-toolkit-python/blob/master/gitkit_command_tool.py does not make any sense for app engine.

**Comment by RevolutionTech** [comment]
Your comments are fair. We can work on making things a little less painful, starting with an example in googlesamples designed with App Engine in mind. I'll let you know when we have put that up.

**Comment by kno10** [comment]
Any update? The deprecation deadline is soon, and still there is no documentation on how to have a working Google Identity Toolkit with Google AppEngine. :-(

**Comment by wuyanna** [comment]
Discussed in the new issue.

**Comment by dounaka** [comment]
+1 
it will be good to publish a sample 
thank you

**Comment by sthomp** [comment]
+1 Any updates? I've spent hours trying to get this working on app engine

**Comment by bill405** [comment]
I agree, sample would be helpful.

**Comment by kno10** [comment]
I have disabled/abandoned Google Identity Toolkit, because it did not work with Google AppEngine.
