### ISSUE TITLE
Deprecation and migration to Firebase

### ISSUE THREAD

**Issue by danielfaust** [google/identity-toolkit-python-client#20]
Is this library deprecated?

https://developers.google.com/identity/toolkit/ states that

> The newest version of Google Identity Toolkit has been released as Firebase Authentication. It includes upgraded client SDKs, open source UI libraries, session management and integrated email sending service for forgotten password flows.
> 
> New projects should use Firebase Authentication. To migrate an existing project from Identity Toolkit to Firebase Authentication, see the migration guide.

When checking the migration site, there aren't really a lot of precise infos.

First off, I think it's really great that this will give us now access to all of the Firebase offerings, as I was in some kind of need for the Cloud Messaging feature.

My question is, how do we replace this library in our Python backend server?

As I have understood the migration guide, an Android App authenticates to Firebase, requests a JWT token from the Firebase server, and our custom Python backend only has to receive this token, verify its validity and extract the info, both with the help of a JWT library, in order to create a new session? This means that server-side now only a JWT library from https://jwt.io/ is needed?

And the same goes for a JavaScript WebApp?

**Comment by liujin-google** [comment]
Right - to create a user session, your python backend server only needs a JWT library to verify the Firebase Auth token (signature and audience) in the request and extract the user info from the token payload. The validation logic is the same for all client apps (Android, iOS and web).

**Comment by danielfaust** [comment]
Thank you for the information.
