### ISSUE TITLE
Not Python3 compatible

### ISSUE THREAD

**Issue by vmenezes** [google/identity-toolkit-python-client#6]
This module use plenty of libraries and few syntax that are deprecated on Python3. Is there anyone working on an update? 
If not, I did some fixes on it and ended up with a new fork that runs on both Python2.x and Python3.x. Should I make a pull request?

**Comment by liujin-google** [comment]
Hi vmenezes, yes, pull requests are welcome!

**Comment by RevolutionTech** [comment]
Thanks for your contributions, Victor!
